### ISSUE TITLE
solver.fit error in rcnn\solver.py

### ISSUE THREAD

**Issue by SJTUzhanglj** [precedenceguo/mx-rcnn#10]
I followed the step to train the model as you suggested.
I only used a command: 
python -m tools.train_alternate   
with default conmand line params and meet an error:

Traceback (most recent call last):
  File "D:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "D:\mx-rcnn-master\tools\train_alternate.py", line 210, in <module>
    args.kv_store, args.work_load_list)
  File "D:\mx-rcnn-master\tools\train_alternate.py", line 138, in alternate_train
    'model/rpn1', ctx, begin_epoch, rpn_epoch, frequent, kv_store, work_load_list)
  File "D:\mx-rcnn-master\tools\train_alternate.py", line 62, in train_rpn
    solver.fit(train_data, frequent=frequent)
  File "rcnn\solver.py", line 106, in fit
    max_label_shape=max_label_shape
TypeError: _train_multi_device() got an unexpected keyword argument 'mutable_data_shape'

Then i find that the last 3 parameters of _train_multi_device function are unexpected keyword as above. But i comment these 3 params, only to meet another error about data.shape.

is this a bug?  Or due to my wrong operations?

**Comment by SJTUzhanglj** [comment]
I thought you applied distributed training, so the rcnn part is different from the dmlc/mxnet example. But can you provide one without distributed training

**Comment by precedenceguo** [comment]
Install a forked MXNet at [MXNet-detection](https://github.com/precedenceguo/mxnet/tree/detection). Follow the instructions at http://mxnet.readthedocs.io/en/latest/how_to/build.html. Install the python interface. We are working to use module API and deprecate this fork asap. However right now please try a special fix at this fork.

Note: the fork is at detection branch. Try `git checkout detection`.

**Comment by SJTUzhanglj** [comment]
I installed the detection branch this time, but a similiar problem happened. 

INFO:root:########## TRAIN RPN WITH IMAGENET INIT
voc_2007_trainval gt roidb loaded from F:\mx-rcnn\data\cache\voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
providing maximum shape [('data', (1, 3, 1000, 1000))] [('label', (1L, 35721L)), ('bbox_target', (1L, 36L, 63L, 63L)), ('bbox_inside_weight', (1L, 36L, 63L, 63L)), ('bbox_outside_weight', (1L, 36L, 63L, 63L))]
Traceback (most recent call last):
  File "D:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\mx-rcnn\tools\train_alternate.py", line 209, in <module>
    args.kv_store, args.work_load_list)
  File "F:\mx-rcnn\tools\train_alternate.py", line 137, in alternate_train
    'model/rpn1', ctx, begin_epoch, rpn_epoch, frequent, kv_store, work_load_list)
  File "F:\mx-rcnn\tools\train_alternate.py", line 61, in train_rpn
    solver.fit(train_data, frequent=frequent)
  File "rcnn\solver.py", line 105, in fit
    max_label_shape=max_label_shape)
TypeError: _train_multi_device() got an unexpected keyword argument 'max_label_shape'

And I checked the model.py in mxnet/python/mxnet/model.py and find the function '_train_multi_device' lost one param.

_train_multi_device(self.symbol, self.ctx, arg_names, param_names, aux_names,
                            self.arg_params, self.aux_params,
                            begin_epoch=self.begin_epoch, end_epoch=self.num_epoch,
                            epoch_size=self.epoch_size,
                            optimizer=optimizer,
                            train_data=data, eval_data=eval_data,
                            eval_metric=eval_metric,
                            epoch_end_callback=epoch_end_callback,
                            batch_end_callback=batch_end_callback,
                            kvstore=kvstore, update_on_kvstore=update_on_kvstore,
                            logger=logger, work_load_list=work_load_list, monitor=monitor,
                            eval_batch_end_callback=eval_batch_end_callback,
                            sym_gen=self.sym_gen)

In solver.py, it's 

mx.model._train_multi_device(self.symbol, self.ctx, self.arg_names, self.param_names, self.aux_names,
                                     self.arg_params, self.aux_params, self.begin_epoch, self.num_epoch,
                                     epoch_size=None, optimizer=self.optimizer,
                                     kvstore=kvstore, update_on_kvstore=update_on_kvstore,
                                     train_data=train_data, eval_data=None, eval_metric=eval_metrics,
                                     epoch_end_callback=epoch_end_callback, batch_end_callback=batch_end_callback,
                                     logger=logger, work_load_list=None, monitor=None,
                                     mutable_data_shape=mutable_data_shape, max_data_shape=max_data_shape,
                                     max_label_shape=max_label_shape)


Anything Wrong?

**Comment by precedenceguo** [comment]
Check the source file at https://github.com/precedenceguo/mxnet/blob/detection/python/mxnet/model.py. The additional parameters are there.

**Comment by SJTUzhanglj** [comment]
Thank you for solving my problem @precedenceguo
