### ISSUE TITLE
ValueError: Must specify all the arguments in args

### ISSUE THREAD

**Issue by SJTUzhanglj** [precedenceguo/mx-rcnn#14]
F:\mx-rcnn>python -m tools.test_final --prefix model/rcnn2

voc_2007_test gt roidb loaded from F:\mx-rcnn\data\cache\voc_2007_test_gt_roidb.pkl
prepare roidb
testing 0/4952
Traceback (most recent call last):
  File "D:\Anaconda2\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "D:\Anaconda2\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "F:\mx-rcnn\tools\test_final.py", line 61, in <module>
    test_net(args.image_set, args.year, args.root_path, args.devkit_path, args.prefix, args.epoch, ctx, args.vis)
  File "F:\mx-rcnn\tools\test_final.py", line 36, in test_net
    pred_eval(detector=detector, test_data=test_data, imdb=voc, vis=vis)
  File "rcnn\tester.py", line 39, in pred_eval
    scores, boxes = detector.im_detect(databatch.data['data'], im_info=databatch.data['im_info'])
  File "rcnn\detector.py", line 57, in im_detect
    grad_req='null', aux_states=self.aux_params)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 783, in bind
    args_handle, args = self._get_ndarray_inputs('args', args, listed_arguments, False)
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 625, in _get_ndarray_inputs
    raise ValueError('Must specify all the arguments in %s' % arg_key)
ValueError: Must specify all the arguments in args

**Comment by precedenceguo** [comment]
Try `combine_model('model/rpn2', rpn_epoch, 'model/rcnn2', rcnn_epoch, 'model/final', 0)` as in `tools/train_alternate.py`.

**Comment by SJTUzhanglj** [comment]
I have combine the model in the last step of training and generate final-0000.params file.You mean using final-0000.params instead of rcnn2-0008.params? But there's no corresponding .json file.

**Comment by precedenceguo** [comment]
Yes, json symbol does not matter.

**Comment by SJTUzhanglj** [comment]
If i want to test my own image with no objective proposal boxes, what should i do

**Comment by precedenceguo** [comment]
Lastest version provide a `demo.py` to serve this purpose. You are welcome to try out a pretrained model if anything incompatible happened.

**Comment by wangg12** [comment]
@precedenceguo I met errors when I run `demo.py` #25.
