### ISSUE TITLE
How much memory is required for mx-rcnn?

### ISSUE THREAD

**Issue by fang289040324** [precedenceguo/mx-rcnn#16]
Hi, I was running in CPU, but the 70G of memory is not enough.
Modified code：
    train_alternate.py
      #ctx = [mx.gpu(int(i)) for i in args.gpu_ids.split(',')]
      ctx = [mx.cpu()]
We need to modify the other place?
Thank you very much.

**Comment by precedenceguo** [comment]
Someone else also informed me of this for GPU, while sadly I cannot reproduce this problem. Running in GPU should use no more than 2G memory for python and no more than 6G gpu memory for solver.

**Comment by dakshvar22** [comment]
@precedenceguo Even I have 3.5 GB of GPU memory available. But I constantly run into this error during '########## TRAIN RCNN WITH IMAGENET INIT AND RPN DETECTION' phase : 

> [07:35:01] /home/tarun/daksh/mxnet/dmlc-core/include/dmlc/./logging.h:300: [07:35:01] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory
> 
> Stack trace returned 12 entries:
> [bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x3c) [0x7f6e38cb4a9c]
> [bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZN5mxnet7storage23GPUPooledStorageManager5AllocEm+0x3bb) [0x7f6e397ccd0b]
> [bt] (2) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZN5mxnet11StorageImpl5AllocEmNS_7ContextE+0x57) [0x7f6e397cfe67]
> [bt] (3) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZNK5mxnet8Resource18get_space_internalEm+0x32) [0x7f6e39850472]
> [bt] (4) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZNK5mxnet8Resource15get_space_typedIN7mshadow3gpuELi1EfEENS2_6TensorIT_XT0_ET1_EENS2_5ShapeIXT0_EEEPNS2_6StreamIS5_EE+0x355) [0x7f6e39c20305]
> [bt] (5) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZN5mxnet2op13ConvolutionOpIN7mshadow3gpuEfE7ForwardERKNS_9OpContextERKSt6vectorINS_5TBlobESaIS9_EERKS8_INS_9OpReqTypeESaISE_EESD_SD_+0x413) [0x7f6e3a27b633]
> [bt] (6) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(+0x119ae2e) [0x7f6e3981ee2e]
> [bt] (7) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZN5mxnet6engine14ThreadedEngine15ExecuteOprBlockENS_10RunContextEPNS0_8OprBlockE+0x98) [0x7f6e397bf548]
> [bt] (8) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0x60) [0x7f6e397c2fe0]
> [bt] (9) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7f6e2fe93c80]
> [bt] (10) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76fa) [0x7f6e58a056fa]
> [bt] (11) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7f6e5873bb5d]
> 
> [07:35:01] /home/tarun/daksh/mxnet/dmlc-core/include/dmlc/./logging.h:300: [07:35:01] src/engine/./threaded_engine.h:336: [07:35:01] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory

**Comment by precedenceguo** [comment]
I would refer you to py-faster-rcnn if you do not have other devices. Otherwise you could consider change config.SCALES = [(300, 500)].
