### ISSUE TITLE
__init__() got an unexpected keyword argument 'fixed_param_names'

### ISSUE THREAD

**Issue by neodooth** [precedenceguo/mx-rcnn#17]
Hi, when trying to train I encountered this error

  File "train_alternate.py", line 26, in alternate_train
    'model/rpn1', ctx, begin_epoch, rpn_epoch, frequent, kv_store, work_load_list)
  File "/some/path/mx-rcnn/tools/train_rpn.py", line 101, in train_rpn
    arg_params=args, aux_params=auxs, begin_epoch=begin_epoch, num_epoch=end_epoch)
  File "/some/path/mxnet/python/mxnet/module/base_module.py", line 333, in fit
    for_training=True, force_rebind=force_rebind)
  File "/some/path/mx-rcnn/rcnn/module.py", line 135, in bind
    fixed_param_names=self._fixed_param_names)
TypeError: __init__() got an unexpected keyword argument 'fixed_param_names'

as I checked the code, mx-rcnn/rcnn/module.py  line 135 is
`module = Module(self._symbol, self._data_names, self._label_names, logger=self.logger,
                        context=self._context, work_load_list=self._work_load_list,
                        fixed_param_names=self._fixed_param_names)`

and the "Module" is
`from mxnet.module.module import Module`

there is no "fixed_param_prefix" in the \__init__ of this "Module". But there is a keyword "fixed_param_prefix" in the \__init__ of "MutableModule". So maybe line 135 should be changed like this?
`module = MutableModule(..., fixed_param_prefix=self._fixed_param_names)`

**Comment by precedenceguo** [comment]
please update to dmlc/mxnet. https://github.com/dmlc/mxnet/blob/master/python/mxnet/module/module.py

**Comment by neodooth** [comment]
thanks, I used yesterday's mxnet.
