### ISSUE TITLE
Different scalar values for smooth_l1 loss

### ISSUE THREAD

**Issue by jonbakerfish** [precedenceguo/mx-rcnn#18]
@precedenceguo Can you explain why we need different scalar values for the smooth_l1 loss? E.g.[`scalar=1.0`](https://github.com/precedenceguo/mx-rcnn/blob/master/rcnn/symbol.py#L108) and [`scalar=3.0`](https://github.com/precedenceguo/mx-rcnn/blob/master/rcnn/symbol.py#L197)

**Comment by precedenceguo** [comment]
c.f. https://github.com/rbgirshick/py-faster-rcnn/issues/89
