### ISSUE TITLE
a question about rcnn training with batch_size > 1

### ISSUE THREAD

**Issue by tornadomeet** [precedenceguo/mx-rcnn#19]
hello, @precedenceguo 
mx-rcnn is a great work!

i just found mx-rcnn support training with batch_size > 1 during train_rcnn() training, it use max size(of the same mini-batch) of each dim to solve different size of each instance, if the dim is shorter than the max dim, then it will pad 0 in the end: 
```python
tensor_list[ind] = np.lib.pad(tensor, pad_shape, 'constant', constant_values=pad)
```
does this will influence the training accuracy? during training, this may changed the input data of roi-pooling, if pad size is too large, then the last area of roi-pooling's output will be meaningless. and during testing, we need no more to pad before roi-pooling, so the behavior maybe changed.

**Comment by precedenceguo** [comment]
The padded zeros are backgrounds which will be neglected because no roi coordinates covering padded regions are supplied to roi-pooling. In other words, they will never be pooled from feature maps.

**Comment by tornadomeet** [comment]
oh, i see, i just read roi-pooling code and found roi-pooling area is determine by rois and spatial_scale. thanks~
