### ISSUE TITLE
problems on converting the pretrained fast-rcnn models

### ISSUE THREAD

**Issue by zjubxl123** [precedenceguo/mx-rcnn#2]
When I used caffe_converter tool provided in mxnet for conversion of pretrained fast rcnn models from https://github.com/rbgirshick/fast-rcnn/blob/master/data/scripts/fetch_fast_rcnn_models.sh, errors occurred saying "google.protobuf.text_format.ParseError: 391:3 : Message type "caffe.LayerParameter" has no field named "roi_pooling_param"."

So is there any help to fix this problem ?

**Comment by precedenceguo** [comment]
This was due to a custom layer in caffe. caffe_converter supports conversion with and without caffe installed.Try with caffe-fast-rcnn branch.

**Comment by zjubxl123** [comment]
thanks. I installed the caffe version of caffe-fast-rcnn branch. Maybe the problem is due to the mxnet version is not installed well. Please refer to this issue:
the errors when installing mx-rcnn #3

Is there any help to fix this problem?  thanks in advance.

**Comment by precedenceguo** [comment]
Caffe converter is fixed now. Please use carefully.
