### ISSUE TITLE
Provide detailed results

### ISSUE THREAD

**Issue by jonbakerfish** [precedenceguo/mx-rcnn#20]
It would be helpful if this repo can provide detailed results. E.g. [faster_rcnn/README.md](https://github.com/ShaoqingRen/faster_rcnn/blob/master/README.md#main-results)

**Comment by precedenceguo** [comment]
Equivalent reproduction with single device. Converge process went slightly slower with multiple devices. Demo model are trained on voc 2007 trainval, following py-faster-rcnn practice. Evaluation can be done as `python test.py --has_rpn --prefix model/demo --epoch 0 --gpu 0`.

**Comment by argman** [comment]
@precedenceguo ,tks for this great work, can you provide your inference time for VGG or resnet?

**Comment by precedenceguo** [comment]
Inference time is relevant to hardware. Please refer to https://github.com/rbgirshick/py-faster-rcnn.

**Comment by argman** [comment]
@precedenceguo , yes, vgg on my machine(k40m) cost about 0.198s/img, i think this is different between caffe and mxnet, and in py-frcnn, the rpn layer is implemented in python, this may cause data exchange, is it faster in mxnet?

**Comment by precedenceguo** [comment]
I did not release any cython speedup for the sake of simplicity so the speed comparison would be fair.

**Comment by Maofei** [comment]
Hi @argman, how about the speed performance of your experiment on different frameworks? 
Are they comparable between caffe and mxnet?
My results show that mxnet is actually much slower in test time.(mxnet ~ 2s, caffe ~ 0.7s)

**Comment by argman** [comment]
@Maofei , I didn't try mxnet, but on caffe, ZF5 taks about 0.075s/img, and VGG takes about 0.198s/img on       pascal voc

**Comment by tornadomeet** [comment]
@Maofei @precedenceguo @argman there is a bug in proposal.py when in inference,  i fixed it by https://github.com/tornadomeet/mx-rcnn/commit/24d28d4d1d1a7d6e4cbdd13e3e5707ab3c872f03   

```is_train``` is string actually, not boolean, so  it will set self.cfg_key = "TRAIN" all the time, and then will use ```config.TRAIN.RPN_POST_NMS_TOP_N = 6000``` not ```config.TEST.RPN_POST_NMS_TOP_N = 300```, this will bring much calculation after roi-pooling, and will slow the test phase.

**Comment by precedenceguo** [comment]
I don't think speed is substantially slower than caffe. Experiment reports roughly 0.15 s/img.

**Comment by precedenceguo** [comment]
0.75s/img on Titan X (Maxwell) with CUDA8.0 + cuDNN5.1 on Ubuntu 14.04.
