### ISSUE TITLE
max_data_shapes/max_label_shape in MutableModule

### ISSUE THREAD

**Issue by tornadomeet** [precedenceguo/mx-rcnn#21]
hello,
i just find when using MutableModule, it need pass max_data_shapes/max_label_shape parameter, but in the function rcnn.module.forward(), if the shape_changed=True, then we should bind the graph again, so  max_data_shapes/max_label_shape seems play no  part in MutableModule, and can we just use the first iter's data_shape instead of max_shape? thanks.

**Comment by precedenceguo** [comment]
Yes. In this case DataIter should return the maximum shape when it is called for the first time.

**Comment by tornadomeet** [comment]
get it, thanks!
