### ISSUE TITLE
memory leak?

### ISSUE THREAD

**Issue by neodooth** [precedenceguo/mx-rcnn#22]
Hi, I tried to use this great work to train on the imagenet, but in the rcnn step, the memory grows continuously, and after ~14k iterations (batch 2) the program is killed by the system since the memory is used up (128gb).

I noticed this phenomenon in the rpn step too, but the rcnn step loads way more data to memory than rpn step so rcnn is killed and rpn is not.

Has anyone met this problem?

Also I found that the memory won't go up if I keep using one same image to train.

**Comment by precedenceguo** [comment]
This seems complicated. You must have generated proposals from your rpn right now. So please follow https://github.com/precedenceguo/mx-rcnn/blob/master/test/test_data_iter.py and call `data_iter.next()` until all data have been processed while watch memory consumption.

This will help determine whether data io cost memory or other problems.

**Comment by neodooth** [comment]
I think mx.nd.array in ROIIter.get_batch does not release itself

**Comment by neodooth** [comment]
https://github.com/dmlc/mxnet/issues/3055

**Comment by precedenceguo** [comment]
Well mx.io.DataIter must return mx.ndarray.NDArray, so there is no workaround to use numpy.ndarray for memory release. Let's wait for mxnet response.

**Comment by neodooth** [comment]
Yes, it's a problem of the memory allocation algorithm of mxnet (PooledStorageManager).
