### ISSUE TITLE
reshape in symbol of get_vgg_rcnn()

### ISSUE THREAD

**Issue by tornadomeet** [precedenceguo/mx-rcnn#24]
hi, @precedenceguo 
why reshape at last in https://github.com/precedenceguo/mx-rcnn/blob/master/rcnn/symbol.py#L114-L115,  does it related to the data iter or something else? thanks.

**Comment by precedenceguo** [comment]
The data parallelism require all data/label to have the same batch size, i.e. the first dimension of data. So the reshape is necessary.

**Comment by tornadomeet** [comment]
i find that in the _split_input_slice(), it need not every device own the same batch number: https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L13, the last devices may have different batch number than others.   
so does ```The data parallelism require all data/label to have the same batch size``` mean here or some else?

**Comment by precedenceguo** [comment]
To put it in another way, all data/label/output must share the same slices. Slices are determined by batch size. Therefore all data/label/output must have the same batch size, hence the reshape. https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L260

**Comment by tornadomeet** [comment]
got it now!
the reason is that roi-pooling will change the first dim, but the slice only remember the corresponding first dim before roi-pooling, so will reshape it back for data parallelism. 
thanks.
