### ISSUE TITLE
Failed to test demo.py

### ISSUE THREAD

**Issue by wangg12** [precedenceguo/mx-rcnn#25]
Hi, there are some errors when I try to test `demo.py` of `rcnn` in `mxnet/example` by `python   demo.py --prefix final --epoch 0 --image myimage.jpg --gpu 0`. The errors are as follows,
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/net/wanggu/anaconda3/lib/python3.5/site-packages/mxnet-0.7.0-py3.5.egg/mxnet/operator.py", line 600, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() keywords must be strings
Segmentation fault (core dumped)
```
How can I solve it? Thanks.
This may be a problem related to python3 compatibility.

**Comment by precedenceguo** [comment]
Did you figure out how this can be solved? If so would you please provide information for others to use?

**Comment by wangg12** [comment]
It seems mxnet has some problem with python3, so I change back to python2.7.  Refer to dmlc/mxnet#3130
