### ISSUE TITLE
final-0000.params 

### ISSUE THREAD

**Issue by Aspirinkb** [precedenceguo/mx-rcnn#26]
The demo.py used the final-0000.params, but how it came out, by which data set and training details?

**Comment by precedenceguo** [comment]
I am sorry this information got missing during some mistakes on updating readme. This is modeled after the demo in py-faster-rcnn, which is trained from voc07 trainval using `train_alternate.py` without any modification or trick.

**Comment by Walid-Ahmed** [comment]
from where can I download 
final-0000.params ?

Thanks
