### ISSUE TITLE
Check failed: (param_.workspace) >= (required_size)

### ISSUE THREAD

**Issue by zhyj3038** [precedenceguo/mx-rcnn#28]
hello, I run mx_rcnn , but itraise following error: 
/home/ubuntu/mxnet/dmlc-core/include/dmlc/logging.h:235: [10:48:17] src/operator/./convolution-inl.h:296: Check failed: (param_.workspace) >= (required_size) 
Minimum workspace size: 1228800000 Bytes
Given: 1073741824 Bytes

I decreased "workspce" paramter  from  in vgg16-symbol.json and "max_data_shape" in "train_rpn.py", also installed cudnn, but it seems nothing changes , would you please  help me ?

**Comment by precedenceguo** [comment]
Make sure mxnet is compiled with cudnn first. Don't modify workspace for convolution and max_data_shape.

**Comment by zhyj3038** [comment]
problem solved wen install **CUDNN** properly, thanks a lot

**Comment by alysazhang** [comment]
Hi, sorry to disturber you. I have met the same problem, when I run demo.py on CPU. Could this be possible running on CPU?
