### ISSUE TITLE
the errors when installing mx-rcnn

### ISSUE THREAD

**Issue by zjubxl123** [precedenceguo/mx-rcnn#3]
I used the versions of mxnet and mshadow you forked in your repository, however, errors occurred as follows when I was making mxnet.

/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::gpu, 2, DType>, const mshadow::Tensor<mshadow::gpu, 2, DType>&, const mshadow::Tensor<mshadow::gpu, 1, DType>&)
 inline void SoftmaxGrad(Tensor<gpu, 2, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   mismatched types ‘mshadow::gpu’ and ‘mshadow::cpu’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, mshadow::half::half_t>’ is not derived from ‘mshadow::Tensor<mshadow::gpu, 2, DType>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, mshadow::half::half_t>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&, const DType&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, mshadow::half::half_t>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
src/operator/./softmax_output-inl.h: In instantiation of ‘void mxnet::op::SoftmaxOutputOp<xpu, DType>::Backward(const mxnet::OpContext&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&) [with xpu = mshadow::cpu; DType = double]’:
src/operator/softmax_output.cc:44:1:   required from here
src/operator/./softmax_output-inl.h:116:78: error: no matching function for call to ‘SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 2, double>&, mshadow::Tensor<mshadow::cpu, 2, double>&, mshadow::Tensor<mshadow::cpu, 1, double>&, double)’
src/operator/./softmax_output-inl.h:116:78: note: candidates are:
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:275:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 2, DType>, const mshadow::Tensor<mshadow::cpu, 2, DType>&, const mshadow::Tensor<mshadow::cpu, 1, DType>&)
 inline void SoftmaxGrad(Tensor<cpu, 2, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:275:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   candidate expects 3 arguments, 4 provided
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
In file included from include/mxnet/./base.h:13:0,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::gpu, 2, DType>, const mshadow::Tensor<mshadow::gpu, 2, DType>&, const mshadow::Tensor<mshadow::gpu, 1, DType>&)
 inline void SoftmaxGrad(Tensor<gpu, 2, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   mismatched types ‘mshadow::gpu’ and ‘mshadow::cpu’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, double>’ is not derived from ‘mshadow::Tensor<mshadow::gpu, 2, DType>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, double>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&, const DType&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, double>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
src/operator/./softmax_output-inl.h: In instantiation of ‘void mxnet::op::SoftmaxOutputOp<xpu, DType>::Backward(const mxnet::OpContext&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&, const std::vector<mxnet::OpReqType>&, const std::vector<mshadow::TBlob>&, const std::vector<mshadow::TBlob>&) [with xpu = mshadow::cpu; DType = float]’:
src/operator/softmax_output.cc:44:1:   required from here
src/operator/./softmax_output-inl.h:116:78: error: no matching function for call to ‘SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 2, float>&, mshadow::Tensor<mshadow::cpu, 2, float>&, mshadow::Tensor<mshadow::cpu, 1, float>&, float)’
src/operator/./softmax_output-inl.h:116:78: note: candidates are:
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:275:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 2, DType>, const mshadow::Tensor<mshadow::cpu, 2, DType>&, const mshadow::Tensor<mshadow::cpu, 1, DType>&)
 inline void SoftmaxGrad(Tensor<cpu, 2, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:275:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   candidate expects 3 arguments, 4 provided
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
In file included from include/mxnet/./base.h:13:0,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::gpu, 2, DType>, const mshadow::Tensor<mshadow::gpu, 2, DType>&, const mshadow::Tensor<mshadow::gpu, 1, DType>&)
 inline void SoftmaxGrad(Tensor<gpu, 2, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:668:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   mismatched types ‘mshadow::gpu’ and ‘mshadow::cpu’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, float>’ is not derived from ‘mshadow::Tensor<mshadow::gpu, 2, DType>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:291:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, float>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
In file included from /home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/tensor.h:816:0,
                 from include/mxnet/./base.h:13,
                 from include/mxnet/operator.h:18,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note: template<class DType> void mshadow::SoftmaxGrad(mshadow::Tensor<mshadow::cpu, 3, Dtype>, const mshadow::Tensor<mshadow::cpu, 3, Dtype>&, const mshadow::Tensor<mshadow::cpu, 2, DType>&, const DType&)
 inline void SoftmaxGrad(Tensor<cpu, 3, DType> dst,
             ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/mshadow/mshadow/./tensor_cpu-inl.h:309:13: note:   template argument deduction/substitution failed:
In file included from src/operator/softmax_output.cc:7:0:
src/operator/./softmax_output-inl.h:116:78: note:   template argument ‘2’ does not match ‘#‘integer_cst’ not supported by dump_decl#<declaration error>’
         SoftmaxGrad(grad, out, label, static_cast<DType>(param_.ignore_label));
                                                                              ^
src/operator/./softmax_output-inl.h:116:78: note:   ‘mshadow::Tensor<mshadow::cpu, 2, float>’ is not derived from ‘mshadow::Tensor<mshadow::cpu, 3, Dtype>’
In file included from src/operator/./softmax_output-inl.h:11:0,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/dmlc-core/include/dmlc/parameter.h:254:43: warning: ‘mxnet::op::__make__SoftmaxOutputParamParamManager__’ defined but not used [-Wunused-variable]
   static ::dmlc::parameter::ParamManager &__make__ ## PType ## ParamManager__ = \
                                           ^
src/operator/softmax_output.cc:30:1: note: in expansion of macro ‘DMLC_REGISTER_PARAMETER’
 DMLC_REGISTER_PARAMETER(SoftmaxOutputParam);
 ^
In file included from include/mxnet/operator.h:13:0,
                 from src/operator/./softmax_output-inl.h:12,
                 from src/operator/softmax_output.cc:7:
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/dmlc-core/include/dmlc/registry.h:218:22: warning: ‘mxnet::op::__make_OperatorPropertyReg_SoftmaxOutput__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/mxnet/operator.h:538:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::mxnet::OperatorPropertyReg, OperatorPropertyReg, name) \
   ^
src/operator/softmax_output.cc:32:1: note: in expansion of macro ‘MXNET_REGISTER_OP_PROPERTY’
 MXNET_REGISTER_OP_PROPERTY(SoftmaxOutput, SoftmaxOutputProp)
 ^
/home/dl/mxnet-RCNN/mxnet-master-precedenceguo-forked/dmlc-core/include/dmlc/registry.h:218:22: warning: ‘mxnet::op::__make_OperatorPropertyReg_Softmax__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
                      ^
include/mxnet/operator.h:538:3: note: in expansion of macro ‘DMLC_REGISTRY_REGISTER’
   DMLC_REGISTRY_REGISTER(::mxnet::OperatorPropertyReg, OperatorPropertyReg, name) \
   ^
src/operator/softmax_output.cc:38:1: note: in expansion of macro ‘MXNET_REGISTER_OP_PROPERTY’
 MXNET_REGISTER_OP_PROPERTY(Softmax, DeprecatedSoftmaxProp)
 ^
make: *** [build/src/operator/softmax_output.o] Error 1

Is there any ideas to fix it?  thanks.

**Comment by precedenceguo** [comment]
Please try latest version of mxnet in dmlc repository.

**Comment by zjubxl123** [comment]
so your idea is to use the latest mxnet in DMLC's repository and mshadow version in your repository ? (because i see you have modified the mshadow in DMLC, such as adding tensor_gpu_roipooling-inl.cuh)

**Comment by precedenceguo** [comment]
Sorry for the misleading clues. This example works without any additional modification to mxnet or mshadow. Just use mxnet and mshadow from dmlc with a version that has `ROIPooling` and `smooth_l1`. This repository is the same as in `mxnet/example/rcnn` but may reflect some experimental changes in the future.

**Comment by zjubxl123** [comment]
thanks a lot. I will have a try.

**Comment by zjubxl123** [comment]
the version of mxnet is finally installed. And python train.py is without error, and the training process is normal.Then i try to use your demo, which requires first to convert the fast-rcnn caffemodel into the mxnet format. I followed your instructions, but when I try to convert the models together with its .prototxt files downloaded by using
https://github.com/rbgirshick/fast-rcnn/blob/master/data/scripts/fetch_fast_rcnn_models.sh,

errors occurred again, showing
Traceback (most recent call last):
  File "convert_model.py", line 99, in <module>
    main()
  File "convert_model.py", line 36, in main
    prob = proto2symbol(args.caffe_prototxt)
  File "/home/dl/mxnet-RCNN/mxnet-org-20160523/tools/caffe_converter/convert_symbol.py", line 152, in proto2symbol
    sym, output_name = proto2script(proto_file)
  File "/home/dl/mxnet-RCNN/mxnet-org-20160523/tools/caffe_converter/convert_symbol.py", line 127, in proto2script
    raise Exception('Unknown Layer %s!' % layer[i].type)
Exception: Unknown Layer Python!

I have installed the fast-rcnn version of Caffe, and caffe.proto does contain the PythonParameter. I am wondering why the above error occurred... Is there any idea?

**Comment by precedenceguo** [comment]
Glad to know that. Just use the model you trained as the demo model.

**Comment by zjubxl123** [comment]
I gave up loading the pretrained fast rcnn models. I trained the fast-rcnn model by myself based on the downloaded VGG16 model, by using the command: python train.py. 

Then, I try to use the command: python demo.py, to load the fast-rcnn model I trained to for object detection in two demo images, however, errors occurred saying:
Traceback (most recent call last):
  File "demo.py", line 32, in <module>
    demo_net(detector, os.path.join(os.getcwd(), 'data', 'demo', '000004'))
  File "/home/dl/mxnet-RCNN/mxnet-org-20160523/example/mx-rcnn-master/tools/demo_net.py", line 28, in demo_net
    roi_array = sio.loadmat(image_name + '_boxes.mat')['boxes']
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 125, in loadmat
    MR = mat_reader_factory(file_name, appendmat, **kwargs)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 55, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/miobase.py", line 236, in get_matfile_version
    % ret)
ValueError: Unknown mat file type, version 47, 47

So, is there any help to fix this problem ? thanks

**Comment by precedenceguo** [comment]
Closed as training works and moved to #4
