### ISSUE TITLE
problem python train_alternate.py --gpus 0. 

### ISSUE THREAD

**Issue by darrylbobo** [precedenceguo/mx-rcnn#32]
Hi, when I ran python train_alternate.py --gpus 0. 

it reported error as below: 

libdc1394 error: Failed to initialize libdc1394
INFO:root:########## TRAIN RPN WITH IMAGENET INIT
voc_2007_trainval gt roidb loaded from /mxnet/example/rcnn/data/cache/voc_2007_trainval_gt_roidb.pkl
append flipped images to roidb
prepare roidb
providing maximum shape [('data', (1, 3, 1000, 1000))] [('label', (1, 34596)), ('bbox_target', (1, 36, 62, 62)), ('bbox_inside_weight', (1, 36, 62, 62)), ('bbox_outside_weight', (1, 36, 62, 62))]
Traceback (most recent call last):
  File "train_alternate.py", line 104, in <module>
    args.frequent, args.kv_store, args.work_load_list)
  File "train_alternate.py", line 26, in alternate_train
    'model/rpn1', ctx, begin_epoch, rpn_epoch, frequent, kv_store, work_load_list)
  File "/mxnet/example/rcnn/tools/train_rpn.py", line 54, in train_rpn
    args, auxs = load_param(pretrained, epoch, convert=True)
ValueError: too many values to unpack

**Comment by precedenceguo** [comment]
Thanks for reporting this. It needs a while to update that. Right now just change it to
`args, auxs, _ = load_param(pretrained, epoch, convert=True)`

**Comment by precedenceguo** [comment]
The third parameters is `num_classes`. Updates to mxnet/example need a while to verify. You could also try this repo.

**Comment by precedenceguo** [comment]
This has been resolved in dmlc/mxnet
