### ISSUE TITLE
Is the result of demo right?

### ISSUE THREAD

**Issue by KeyKy** [precedenceguo/mx-rcnn#33]
I use the following arguments:
python demo.py --prefix final --epoch 0 --image data/VOCdevkit2007/VOC2007/JPEGImages/000001.jpg --gpu 2

and the results is:
person [  69.18438721    5.09894276  599.          822.22625732] 0.998187

but the width and height of 000001.jpg is (353, 500), the above box is out of border. is it fine?

**Comment by precedenceguo** [comment]
According to paper, image is resized to 600 pixel for the short side.

**Comment by KeyKy** [comment]
Oh, I see the code of im_array. It has been resized. Thanks
