### ISSUE TITLE
Custom Training: Training on custom dataset

### ISSUE THREAD

**Issue by dubur** [precedenceguo/mx-rcnn#36]
I have a question about training mx-rcnn on cutstom datasets, does the preparation steps for training is the same to py-faster-rcnn? I went through the io interface of pascal_voc and it didn't contain any rpn_roidb loading functions, did I miss anything?

**Comment by precedenceguo** [comment]
The interface is IMDB, slightly different from py-faster-rcnn. load_rpn_roidb is inherited from IMDB

**Comment by Ram124** [comment]
@ijkguo 
What all need to be changed to work on own dataset?
I have 2  classes.
i have 300 Images of each class.

Can You tell me in details.

Thank You,
Any help is really appreciated.
