### ISSUE TITLE
how to use the demo.py

### ISSUE THREAD

**Issue by zjubxl123** [precedenceguo/mx-rcnn#4]
May I ask how to use the demo.py ? Since, now there is no data in the data folder.... Previously, there is two images as well as their bounding boxes in .mat format. However, when use the command "python demo.py", errors occurred saying that Unknown mat file type....

Is there any help ? thanks

**Comment by precedenceguo** [comment]
A closer look at the error would point to the function `scipy.io.loadmat` which loads data from matlab serial file `.mat`. Similar issues were reported to the scipy community and posted on stackoverflow. You are more than welcome to post your solution after you fix this.

**Comment by precedenceguo** [comment]
Do we have an update on this?

**Comment by zjubxl123** [comment]
not yet. I found there is no data in the data folder of mx-rcnn in your reporsitory...

**Comment by precedenceguo** [comment]
That is set by design. Please download the demo data as instructed in README.

**Comment by precedenceguo** [comment]
Close as we don't have this demo anymore.
