### ISSUE TITLE
final-0000.params

### ISSUE THREAD

**Issue by Walid-Ahmed** [precedenceguo/mx-rcnn#41]
from where can I download 
final-0000.params ?

Thanks

**Comment by precedenceguo** [comment]
It is on the README.

Download link to trained model Baidu Yun: http://pan.baidu.com/s/1boRhGvH (ixiw) or Dropbox: https://www.dropbox.com/s/jrr83q0ai2ckltq/final-0000.params.tar.gz?dl=0
