### ISSUE TITLE
What's next?

### ISSUE THREAD

**Issue by precedenceguo** [precedenceguo/mx-rcnn#44]
Now that we have support for ResNet and COCO, it is time to think about what's next in this project.
![example](https://cloud.githubusercontent.com/assets/13162287/22101032/92085dc0-de6c-11e6-9228-67e72606ddbc.png)

* Full parallelization support that scales to 8 gpus.
* Standard detection io. Check [ssd plan](https://github.com/dmlc/mxnet/issues/4225).

**Comment by atticcas** [comment]
Thanks for your update! 

Absolutely Great work here! Looking forward to new updates!
