### ISSUE TITLE
AttributeError: 'module' object has no attribute 'Proposal'

### ISSUE THREAD

**Issue by iFighting** [precedenceguo/mx-rcnn#45]
i just run the demo,it show the error:
Traceback (most recent call last):
  File "demo.py", line 139, in <module>
    main()
  File "demo.py", line 117, in main
    symbol = get_vgg_test()
  File "/home/mx-rcnn/rcnn/symbol/symbol_vgg.py", line 276, in get_vgg_test
    rois = mx.symbol.Proposal(
AttributeError: 'module' object has no attribute 'Proposal'

**Comment by iFighting** [comment]
your code has many bugs in my computer
i just doubt that do you run the training code?

**Comment by precedenceguo** [comment]
Install [MXNet](https://github.com/precedenceguo/mxnet/tree/simple)

**Comment by iFighting** [comment]
i hava installed mxnet
now i can run the demo and train the model
what i want to say is that your code still has many bugs:

1.in the symbol_vgg.py, i just commeted if config.TEST.CXX_PROPOSAL,group = mx.symbol.Proposal, and use group = mx.symbol.Custom().
Is there any difference?
2.in the rcnn/core/loader.py, there is a bug,in the line, you should append if len(row_perm) > 0:,otherwise inds[:-extra] = np.reshape(inds_[row_perm, :], (-1,)) will get error
3.in the demo.py code, you should add if len(keep) == 0:
etc

**Comment by precedenceguo** [comment]
1. faster
2. I can't follow you.... You mean when len(row_perm) == 0, inds_[row_perm, :] will get error? Yet numpy should support blank indexing?
```
a = np.zeros((0, 2))
b = []
c = a[b]
```
3. follows 2

Thanks very much. Any ideas to correct them?

**Comment by iFighting** [comment]
my numpy is too old?
i know.
all the bugs just from the blank indexing, the old numpy does not support it!
thanks!
can you speak chinese?

**Comment by precedenceguo** [comment]
I think numpy 1.8.2 works with blank indexing.

**Comment by iFighting** [comment]
when it begin train, i have met an error:
<img width="1275" alt="screen shot 2017-01-12 at 7 50 18 pm" src="https://cloud.githubusercontent.com/assets/6366788/21890104/108fe124-d907-11e6-8bfe-7fcaf979adb0.png">

**Comment by precedenceguo** [comment]
I do not know. What experiment are you doing now?

**Comment by iFighting** [comment]
I have solved the problem.
I just set a smaller value to the batchsize, no it works well.

**Comment by iFighting** [comment]
i installed the version you give me(https://github.com/precedenceguo/mxnet/tree/simple) 
it still have:AttributeError: 'module' object has no attribute 'Proposal'
why?

**Comment by iFighting** [comment]
another problem
when i change the batchsize smaller in rcnn/config.py and train_end_to_end.py.
i found that GPU used is not changed(seems always 3800MB around)
I have changed the batchsize very small(config.TRAIN.BATCH_ROIS=16,config.TRAIN.RPN_BATCH_SIZE=32)
do you know why?

**Comment by precedenceguo** [comment]
No idea but we may have traded VGG memory usage for efficiency. You may want to try ResNet-101 which uses almost the same amount of memory.

**Comment by xioryu** [comment]
Well, I installed the forked mxnet but failed to load the module mxnet.symbol.Proposal when running test.py.  How do I load this op? (PS: i m a beginner of mxnet xD:)

**Comment by precedenceguo** [comment]
git clone https://github.com/precedenceguo/mx-rcnn.git --recursive -b simple
cd mx-rcnn
make
cd python
python setup.py install --user

**Comment by iFighting** [comment]
sorry,new problem comes.
i train the PASCAL VOC data correctly.
but when i trains my data(2 classes, the data is ok,because i trained it in py-faster-rcnn  correctly)
it has encountered errors(i have train it 2 times, the same error).
i don't know how to solve it.
do you know why?
this it the log:
[23:58:53] /home/img/jiangyi/test/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:58:53] src/operator/custom.cc:79: Check failed: op_info_->forward(ptrs.size(), ptrs.data(), tags.data(),      reqs.data(), ctx.is_train, op_info_->p_forward)
1273 [23:58:53] /home/img/jiangyi/test/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:58:53] src/operator/custom.cc:79: Check failed: op_info_->forward(ptrs.size(), ptrs.data(), tags.data(),      reqs.data(), ctx.is_train, op_info_->p_forward)
1274 [23:58:53] /home/img/jiangyi/test/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:58:53] src/engine/./threaded_engine.h:306: [23:58:53] src/operator/custom.cc:79: Check failed: op_info_-     >forward(ptrs.size(), ptrs.data(), tags.data(), reqs.data(), ctx.is_train, op_info_->p_forward)
1275 An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with de     bugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to emp     ty after debugging.
1276 terminate called after throwing an instance of 'dmlc::Error'
1277 [23:58:53] /home/img/jiangyi/test/mxnet/dmlc-core/include/dmlc/logging.h:235:   what():  [23:58:53] src/engine/./threaded_engine.h:306: [23:58:53] src/operator/custom.cc:79: Check failed     : op_info_->forward(ptrs.size(), ptrs.data(), tags.data(), reqs.data(), ctx.is_train, op_info_->p_forward)
1278 An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with de     bugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to emp     ty after debugging.
1279 [23:58:53] src/engine/./threaded_engine.h:306: [23:58:53] src/operator/custom.cc:79: Check failed: op_info_->forward(ptrs.size(), ptrs.data(), tags.data(), reqs.data(), ctx.is_train, op_     info_->p_forward)
1280 An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with de     bugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to emp     ty after debugging.
1281 terminate called recursively
![image](https://cloud.githubusercontent.com/assets/6366788/22091799/df1e0972-de33-11e6-89ea-9f5f2b459d5a.png)

**Comment by precedenceguo** [comment]
export MXNET_ENGINE_TYPE=NaiveEngine
see what caused the error

**Comment by iFighting** [comment]
when i train my data, it has this error:
it is ok in py-faster-rcnn
it seem that ex_heights is 0, should i modify the bbox_transform.py?
![image](https://cloud.githubusercontent.com/assets/6366788/22274193/f0aec0a4-e2df-11e6-84fa-c2762fb0a643.png)

**Comment by precedenceguo** [comment]
Can this be repeated?

**Comment by iFighting** [comment]
yes, i have met this error in mx-rcnn several times,while in py-faster-rcnn,i have trained several times correctly
i found that in bbox_transform.py of mx-rcnn, the code is not the same with bbox_transform.py in py-faster-rcnn
so i think there maybe have a bug?

**Comment by precedenceguo** [comment]
So after this change did you encounter this error any more?

**Comment by breeze5428** [comment]
I trained my own data with resnet101, and encountered this error:
![screenshot from 2017-02-22 21 01 20](https://cloud.githubusercontent.com/assets/5536634/23212560/4555ab68-f942-11e6-8bc7-385d533ac2c2.png)
PS:   I have not update mx-rcnn since 18 Jan 2017.

**Comment by breeze5428** [comment]
The error is fixed.  Some arguments in the  config.py is not set correctly

**Comment by Ram124** [comment]
@breeze5428 What did you change in config.py??

Even i have got the same error.
Please help
