### ISSUE TITLE
Error in downloading pre-trained model

### ISSUE THREAD

**Issue by dakshvar22** [precedenceguo/mx-rcnn#47]
Hi,

I am trying to download the basic pre-trained model given in the README from this link - https://www.dropbox.com/s/jrr83q0ai2ckltq/final-0000.params.tar.gz?dl=0
I tried multiple times but the download fails after downloading around 320 MB of the file. Tried switching to different networks also, but no luck. Can someone confirm if the file is not corrupted on the link?

For the different link posted - http://pan.baidu.com/share/init?shareid=2372813683&uk=3979418934 , the page seems to be in chinese I think and it asks for some password I guess. Can I get access to that?

Thanks

**Comment by precedenceguo** [comment]
The password is in the brackets Baidu Yun (ixiw).
I will check dropbox link soon.

**Comment by dakshvar22** [comment]
@precedenceguo Similar problem seems to happen with the Baidu link too. Can you check that too please :(

**Comment by dakshvar22** [comment]
@precedenceguo  I managed to download from the dropbox link. Thank you so much :)

**Comment by dakshvar22** [comment]
Running the demo program gives me this error - 

> Traceback (most recent call last):
>   File "demo.py", line 139, in <module>
>     main()
>   File "demo.py", line 119, in main
>     demo_net(predictor, args.image)
>   File "demo.py", line 70, in demo_net
>     scores, boxes, data_dict = im_detect(predictor, data_batch, data_names, im_scale)
>   File "/home/tarun/daksh/mx-rcnn-master/rcnn/core/tester.py", line 106, in im_detect
>     output = predictor.predict(data_batch)
>   File "/home/tarun/daksh/mx-rcnn-master/rcnn/core/tester.py", line 25, in predict
>     self._mod.forward(data_batch)
>   File "/home/tarun/daksh/mx-rcnn-master/rcnn/core/module.py", line 187, in forward
>     shared_module=self._curr_module)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/module/module.py", line 344, in bind
>     grad_req=grad_req, input_types=input_types)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/module/executor_group.py", line 188, in __init__
>     self.label_layouts = self.decide_slices(label_shapes)
>   File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.1-py2.7-linux-x86_64.egg/mxnet/module/executor_group.py", line 203, in decide_slices
>     assert len(data_shapes) > 0
> AssertionError

Can you help out?

**Comment by precedenceguo** [comment]
Yeah this is new error from recent update to nnvm. I will fix it soon.

**Comment by dakshvar22** [comment]
@precedenceguo  okay. In the mean time, I really want to test demo.py and see the results. I assume it should work on your forked version of mxnet. I tried installing that version following the steps of this link -  https://no2147483647.wordpress.com/2015/12/07/deep-learning-for-hackers-with-mxnet-1/ (replaced the repo of git clone with that of yours). But the installation failed. 
Can you give the instructions on how to install your forked version of mxnet?

**Comment by precedenceguo** [comment]
It should be the same as in the guide but make sure you are on the legacy branch.

**Comment by precedenceguo** [comment]
OK I have updated. Please try again. I recommend http://mxnet.io/get_started/ubuntu_setup.html as the installation guide.

**Comment by xioryu** [comment]
A json file "resnet-101-symbol.json" may be better for defining the resnet model.

**Comment by precedenceguo** [comment]
We do not use json file for historic reasons.
