### ISSUE TITLE
Install MXNet with a version that has operators ROIPooling and smooth_l1 appeared

### ISSUE THREAD

**Issue by pby5** [precedenceguo/mx-rcnn#5]
Thanks for your sharing,I had installed mxnet with latest version but no ROIPooling and smooth_l1, did you implement ROIPooling and smooth_l1 yourself or install mxnet with this two layers?

**Comment by precedenceguo** [comment]
Check the `mxnet/src/operator` folder. The folder on https://github.com/dmlc/mxnet/tree/master/src/operator has those operators.

**Comment by precedenceguo** [comment]
Do we have an update on this?

**Comment by pby5** [comment]
it's my wrong, and I update mxnet and now this model can train now

**Comment by precedenceguo** [comment]
Close as it is recommended to use latest mxnet master.
