### ISSUE TITLE
training error with latest version (1/20/17)

### ISSUE THREAD

**Issue by jwnsu** [precedenceguo/mx-rcnn#50]
After checked out latest version (that removed dependency on customized version of mxnet), got following error at the beginning of training:
---
providing maximum shape [('data', (1, 3, 600, 1000)), ('gt_boxes', (1, 100, 5))] [('label', (1, 20646)), ('bbox_target', (1, 36, 37, 62)), ('bbox_weight', (1, 36, 37, 62))]
[20:55:24] /home/dsu/mxnet/dmlc-core/include/dmlc/logging.h:235: [20:55:24] src/symbol/symbol.cc:155: Symbol.InferShapeKeyword argument name bbox_target not found.
-----

Training works fine in previous version. Saw following changes in train_end2end.py that caused the error:
---
    max_data_shape, max_label_shape = train_data.infer_shape(max_data_shape)
    max_data_shape.append(('gt_boxes', (input_batch_size, 100, 5)))
    print 'providing maximum shape', max_data_shape, max_label_shape

    # infer shape
    data_shape_dict = dict(train_data.provide_data + train_data.provide_label)
    arg_shape, out_shape, aux_shape = sym.infer_shape(**data_shape_dict)  <-- error here

**Comment by precedenceguo** [comment]
Cannot reproduce your issue. Did you change anything?

**Comment by jwnsu** [comment]
There are only some very minor changes to test on different dataset. Let me pull the source free and see whether we have same error again.

**Comment by jwnsu** [comment]
After pull fresh source and re-setup, the issue goes away, closing it.
