### ISSUE TITLE
How can I train the data without the pretrained model ?

### ISSUE THREAD

**Issue by MU001999** [precedenceguo/mx-rcnn#52]
1, I can't download the vgg-0000.params, because it not appeared when I open the download link.
2, If I can download the params, I also need to train my data without the pretrained params.
3, When I make the code about arg_params and aux_params between '#' or ''', it will come with the error: out of memory.

I need help, thanks very much !

**Comment by MU001999** [comment]
@precedenceguo

**Comment by precedenceguo** [comment]
You cannot.

Oh, download link is broken. see https://github.com/dmlc/mxnet-model-gallery/blob/master/imagenet-1k-vgg.md

**Comment by MU001999** [comment]
Thanks very much, but could you tell me why cannot ?

**Comment by precedenceguo** [comment]
With the imagenet pretrained model, we don't need to randomly initialize the conv layers. So I did not write the initialization code. So you cannot unless you do it yourself.
