### ISSUE TITLE
trained model with ResNet-101 

### ISSUE THREAD

**Issue by wzkg2012** [precedenceguo/mx-rcnn#53]
I trained the model with ResNet-101 on VOC07+12 , but the performance is lower than what you reported, can you provide the trained model with resnet-101?

**Comment by precedenceguo** [comment]
How much lower? I could certainly provide this model but I am working on something else so no time to verify.

**Comment by wzkg2012** [comment]
I got 77.3% with ResNet-101 on VOC07+12 after 10 epoch, about 2% lower than you reported.  Do more number of epochs get better results?

**Comment by precedenceguo** [comment]
Our result is also from 10th epoch model.

This implementation follows closely to the original paper, except the training counter (mxnet uses epochs, caffe uses iterations). We don't intend to be better but we have close results.
