### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by breeze5428** [precedenceguo/mx-rcnn#54]
I trained mx-rcnn with my data, encountering the following error:

> voc_2007_trainval gt roidb loaded from data/cache/voc_2007_trainval_gt_roidb.pkl
> append flipped images to roidb
> filtered 220000 roidb entries: 220000 -> 0
> Traceback (most recent call last):
>   File "train_end2end.py", line 184, in <module>
>     main()
>   File "train_end2end.py", line 181, in main
>     lr=args.lr, lr_step=args.lr_step)
>   File "train_end2end.py", line 52, in train_net
>     anchor_ratios=config.ANCHOR_RATIOS, aspect_grouping=config.TRAIN.ASPECT_GROUPING)
>   File "/home/weiliu/projects/traffSgn/mx-rcnn/rcnn/core/loader.py", line 269, in __init__
>     self.get_batch()
>   File "/home/weiliu/projects/traffSgn/mx-rcnn/rcnn/core/loader.py", line 355, in get_batch
>     iroidb = [roidb[i] for i in range(islice.start, islice.stop)]
> IndexError: list index out of range
> 

I don not know how to solve it.   Is there any advice?  Thank you in advance.

**Comment by precedenceguo** [comment]
Note "filtered 220000 roidb entries: 220000 -> 0". Something is wrong.

**Comment by breeze5428** [comment]
Thank you.  The error is fixed. Something is wrong with my ,xml files.
