### ISSUE TITLE
AssertionError: Single batch only_

### ISSUE THREAD

**Issue by weiliuxm** [precedenceguo/mx-rcnn#55]
Hi,
I employed  train_end2end.py  to train data.   To train faster,   I  set` config.TRAIN.BATCH_IMAGES = 2` in the  file train_end2end.py.   However, an error is  reported.  

> _Traceback (most recent call last):
>   File "train_end2end.py", line 186, in <module>
>     main()
>   File "train_end2end.py", line 183, in main
>     lr=args.lr, lr_step=args.lr_step)
>   File "train_end2end.py", line 54, in train_net
>     anchor_ratios=config.ANCHOR_RATIOS, aspect_grouping=config.TRAIN.ASPECT_GROUPING)
>   File "/home/weiliu/projects/traffSgn/mx-rcnn/rcnn/core/loader.py", line 269, in __init__
>     self.get_batch()
>   File "/home/weiliu/projects/traffSgn/mx-rcnn/rcnn/core/loader.py", line 356, in get_batch
>     data, label = get_rpn_batch(iroidb)
>   File "/home/weiliu/projects/traffSgn/mx-rcnn/rcnn/io/rpn.py", line 46, in get_rpn_batch
>     assert len(roidb) == 1, 'Single batch only'
> AssertionError: Single batch only_
> 

Any suggestion?  Thank you in advance!

**Comment by precedenceguo** [comment]
"Single batch only" --> "sorry, unimplemented"

**Comment by breeze5428** [comment]
Thank you for reply.

Is `config.TRAIN.BATCH_IMAGES ` not be able to set to be 2?

It works well when `config.TRAIN.BATCH_IMAGES = 2 `in the file of train_end2end.py.

**Comment by precedenceguo** [comment]
Only train_rcnn can do that.

**Comment by breeze5428** [comment]
Thank you.
