### ISSUE TITLE
How to resume  training with a specific epoch  when running train_end2end.py?

### ISSUE THREAD

**Issue by breeze5428** [precedenceguo/mx-rcnn#57]
Hi guys!

I am rookie. I have trained the resnet model using _train_end2end.py_  with 10 epochs successfully.  Now, I want to resume training from the check points, for example continuing training from the 10th epoch.  How to do it?

Sorry to trouble you.  Thank you in advance!

**Comment by precedenceguo** [comment]
`--resume --begin_epoch 10 --end_epoch 15` for 5 more.

**Comment by breeze5428** [comment]
Thank you for reply.
I ran 
> python train_end2end.py --network resnet --gpu 0  --resume --begin_epoch 10 --end_epoch 15

,then an error  reported as follow:
>   File "train_end2end.py", line 182, in main
>     lr=args.lr, lr_step=args.lr_step)
>   File "train_end2end.py", line 131, in train_net
>     lr_scheduler = mx.lr_scheduler.MultiFactorScheduler(lr_iters, lr_factor)
>   File "/home/weiliu/mxnet/python/mxnet/lr_scheduler.py", line 102, in __init__
>     assert isinstance(step, list) and len(step) >= 1
> AssertionError
> 
However, It is normal to run
> python train_end2end.py --network resnet --gpu 0  --end_epoch 10

**Comment by precedenceguo** [comment]
Add `--lr_step 15`, although epoch 15 will be the end. :)

**Comment by breeze5428** [comment]
Ok, now it works well.  Thank you sincerely!
