### ISSUE TITLE
time comsumed for inference

### ISSUE THREAD

**Issue by JacobWang95** [precedenceguo/mx-rcnn#62]
When I was using demo.py to try the detection result, it took several seconds for a single image on Titan X GPU. 
Why it takes such a long time? 
I'm new to MXNet, how can I fix it?

**Comment by precedenceguo** [comment]
There is no trivial answer, nor published solutions due to heterogeneous hardware, different environment, etc.

**Comment by precedenceguo** [comment]
I think you might have encountered cudnn_autotune as in #67.
