### ISSUE TITLE
a question about cudnn autotune

### ISSUE THREAD

**Issue by niluanwudidadi** [precedenceguo/mx-rcnn#64]
@precedenceguo 
why before training faster rcnn, we should export MXNET_CUDNN_AUTOTUNE_DEFAULT=0?
And if I don't export this variable, the terminal will report the cudnn find the algorithem to get best performance in training and testing.
So is cudnn in use when I turn off it?

**Comment by precedenceguo** [comment]
Nobody uses cudnn autotune in full image detection. This repo is just clearer.

**Comment by niluanwudidadi** [comment]
Thank you for your reply! @precedenceguo
