### ISSUE TITLE
lr policy for COCO

### ISSUE THREAD

**Issue by DengpanFu** [precedenceguo/mx-rcnn#65]
I noticed that you have reported a mAP 26.1 on coco_val with Resnet-101 + coco_train.  There are more than 80K images in coco_train, after flipping we will have more than 160K images. So, i am curious about your lr policy, did you keep the same lr policy as pascal_voc(train 10 epoches, and decrease lr at 7th epoch)? if so, that would be more than 1600K iterations for training, while in rbg's py-faster-rcnn, he just train 490K iterations. Could you please give me some advice to reproduce your results, Thanks!

**Comment by precedenceguo** [comment]
Be careful about the iterations in py-faster-rcnn: you have missed some details, while simplicity and clarity are the aim of this repo.

**Comment by DengpanFu** [comment]
Thanks for your reply. I re-checked the config file, for end2end training: e2e_epoch = 10, e2e_lr_step = '7'. If we apply these configs to train resnet with COCO, that will take a very long time with single gpu(compared to py-faster-rcnn's 3 epoches training). I didn't find any scripts implied how to do training with COCO, could you please share your script used for COCO, Thanks!

**Comment by precedenceguo** [comment]
I will just put this in my list, but be sure to checkout other implementations emphasized on performance comparison.
