### ISSUE TITLE
network.resnet.FIXED_PARAMS_SHARED  in config.py

### ISSUE THREAD

**Issue by weiliuxm** [precedenceguo/mx-rcnn#66]
Hi, Guo!
Thank you for sharing your codes.  Could you explain the 

> FIXED_PARAMS_SHARED

  in the following lines from config.py?
```
network.resnet.FIXED_PARAMS = ['conv0', 'stage1', 'gamma', 'beta']
network.resnet.FIXED_PARAMS_SHARED = ['conv0', 'stage1', 'stage2', 'stage3', 'gamma', 'beta']
```

FIXED_PARAMS  indicates network parameters which are fixed. However, I could not make network.resnet.FIXED_PARAMS_SHARED clear by myself.   Does it denote sharing features for RPN and faster R-CNN ?

Thank you in advance!

**Comment by precedenceguo** [comment]
Please refer to the VGG counterpart.
