### ISSUE TITLE
Is this a bug in computing Anchors?

### ISSUE THREAD

**Issue by dongxiao92** [precedenceguo/mx-rcnn#70]
In file operators/proposal-inl.h,line 273
`float w = base_anchor[2] - base_anchor[1] + 1.0f`
should `base_anchor[1]` be `base_anchor[0]`？

**Comment by precedenceguo** [comment]
Yeah thanks for noticing. You are welcome to fix them by pr but I will also put this in my list.

**Comment by precedenceguo** [comment]
-.- sorry for the delay. Please note that base_anchor is a square so nothing went wrong. fixed here https://github.com/precedenceguo/mxnet/commit/ea3d4eb4f5fac9151e35c3a86196b2d198708698.
