### ISSUE TITLE
Issues with pretrained models

### ISSUE THREAD

**Issue by AleBasso80** [precedenceguo/mx-rcnn#71]
Hello,
I'm running the script demo.py. First I tried to use the pretrained models, but I got the error "rpn_conv_3x3_weight not initialized". 
Then I tried to use "get_vgg_rcnn" function instead of the default "get_vgg_test" and I got the error "InferShapeKeyword argument name im_info not found". 
Same issues with the resnet and with the converted caffe py-faster-rcnn model. 
Instead, if I use the final-0000.params model, everything is fine.
Can someone help me to figure it out?

Thanks!

**Comment by precedenceguo** [comment]
faster rcnn is a finetune process from vgg imagenet to voc. need to use the finetuned model final-0000.params model
