### ISSUE TITLE
when run make ,there are error.

### ISSUE THREAD

**Issue by shipeng-uestc** [precedenceguo/mx-rcnn#79]
`cd rcnn/cython/; python setup.py build_ext --inplace; rm -rf build; cd ../../
Traceback (most recent call last):
  File "setup.py", line 62, in <module>
    CUDA = locate_cuda()
  File "setup.py", line 53, in locate_cuda
    for k, v in cudaconfig.iteritems():
AttributeError: 'dict' object has no attribute 'iteritems'
cd rcnn/pycocotools/; python setup.py build_ext --inplace; rm -rf build; cd ../../
Warning: Extension name '_mask' does not match fully qualified name 'rcnn.pycocotools._mask' of '_mask.pyx'
running build_ext
`
I'm using cuda8.0
Can you help me ? How to solve it

**Comment by shuikehuo** [comment]
I have same error.How is the landlord solved?
