### ISSUE TITLE
width key in roidb and tensor_vstack arguments

### ISSUE THREAD

**Issue by qingswu** [precedenceguo/mx-rcnn#8]
Hi, when I tried to train at the first time, I came across a few small issues. 

1. there is no 'width' and 'height' key in roidb, which will raise a key error in 
mx-rcnn/rcnn/loader.py", line 205, in reset
    widths = np.array([r['width'] for r in self.roidb])
2. tensor_vstack only take one argument in image_processing.py, so another error is raised by the second argument.
mx-rcnn/rcnn/loader.py", line 289, in get_batch
    all_label['label'] = tensor_vstack([batch['label'] for batch in new_label_list], pad=-1)

**Comment by precedenceguo** [comment]
Thank you for reporting this!

**Comment by qingswu** [comment]
Looks like it's fixed on my machine, thanks! But I still have another issue with the training, i'll open another issue to address it.
