### ISSUE TITLE
Do I need to compile rcnn/cython package?

### ISSUE THREAD

**Issue by WalterMa** [precedenceguo/mx-rcnn#91]
ReadMe file doesn;t mention anything about is it need to compile rcnn/cython package.
But in rcnn/processing/bbox_transform.py file, it:
`from ..cython.bbox import bbox_overlaps_cython`

Do I need to compile rcnn/cython package before train network?

**Comment by WalterMa** [comment]
OK... I find it was built when invoke make.
While in windows, the cython build failed. 
Does the repo support windows?

**Comment by precedenceguo** [comment]
For now there is a `windows` branch.

**Comment by WalterMa** [comment]
Thanks, it's really helpful. 
I will close this issue.
